EDGE_CREDIT="nxc@127.0.0.1"
PIPELINED=1
DIRNAME="debug"
DIRNAME="debug"
TARGET_DNN_DIR="data/vgg16_base.aspen"
# TARGET_DNN_DIR="data/resnet50_base.aspen"
# TARGET_DNN_DIR="data/bert_base_base.aspen"
# TARGET_DNN_DIR="data/yolov3_base.aspen"
TARGET_NASM_DIR="data/vgg16_B1_T200.nasm"
# TARGET_NASM_DIR="data/resnet50_B8_T800.nasm"
# TARGET_NASM_DIR="data/bert_base_B1_T800.nasm"
# TARGET_NASM_DIR="data/yolov3_B1_T20.nasm"
TARGET_INPUT="data/batched_input_128.bin"
PREFIX="vgg16"
# PREFIX="resnet50"
# PREFIX="bert_base"
# server_ip="127.0.0.1"
server_ip="147.46.130.51"
server_port=62000
# SCHEDULE_POLICY="local"
# SCHEDULE_POLICY="partial"
# SCHEDULE_POLICY="random"
# SCHEDULE_POLICY="dynamic"
# SCHEDULE_POLICY="sequential"
SCHEDULE_POLICY="conventional"
# SCHEDULE_POLICY="conventional+pipeline"
# SCHEDULE_POLICY="spinn"
# SCHEDULE_POLICY="spinn+pipeline"
SCHED_SEQUENTIAL_IDX=1
SCHED_PARTIAL_RATIO=0.1
DSE_NUM=32
OUTPUT_ORDER="cnn"
# OUTPUT_ORDER="transformer"
INFERENCE_REPEAT_NUM=100
NUM_EDGE_DEVICES=3
EDGE_DSE_NUM=2
